apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ry7abb1kd-python
  janus-idp.io/tekton: ry7abb1kd-python
  backstage.io/kubernetes-id: ry7abb1kd-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ry7abb1kd-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
