apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ry7abb1kd-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ry7abb1kd-python 
  name: ry7abb1kd-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ry7abb1kd-python 
